#!/bin/bash

PACKAGES="$HOME/.packages"

if ! command -v gum &> /dev/null; then
  echo "command gum not found ..."
  echo "installing gum ..."
  sudo pacman -S gum --noconfirm
fi

if [ ! -d "$PACKAGES" ]; then
    echo "O diretório $PACKAGES não existe."
    exit 1
fi

LISTS=$(ls "$PACKAGES" | gum choose --no-limit --header "Choose lists to install")

for LIST in $LISTS; do
  yay -S $(cat "$PACKAGES/$LIST" | xargs)
done
