#!/bin/bash

if [ ! -d "$HOME/Pictures" ]; then
    mkdir -p "$HOME/Pictures"
fi

FILENAME="screenshot-$(date +%s).png"

if [ "$1" == "screen" ]; then
    grim "$HOME/Pictures/$FILENAME"
    grim - | wl-copy --type image/png
elif [ "$1" == "area" ]; then
    area=$(slurp)
    if [ "$area" ]; then
        grim -g "$area" "$HOME/Pictures/$FILENAME"
        grim -g "$area" - | wl-copy --type image/png
    else
        echo "Selection canceled!"
    fi
else
    echo "Incorrect usage! Pass 'screen' or 'area' as a parameter."
    exit 1
fi

notify-send "Screenshot copied to clipboard!"

