#!/bin/bash

LIST="$HOME/.config/Code/User/extensions.list"

if [ ! -f "$LIST" ]; then
  echo "File not found: $LIST"
  exit 1
fi

for ext in $(cat "$LIST"); do
  code --install-extension $ext --force
done
