#!/bin/bash

LIST="$HOME/.packages.list"

while IFS= read -r line; do
  if [[ -z "$line" || "$line" == \#* ]]; then
    continue
  fi
  if ! pacman -Q "$line" &>/dev/null; then
    packages+=("$line")
  fi
done < "$LIST"


paru -S "${packages[@]}"
