#!/bin/bash

sudo systemctl enable --now libvirtd
sudo usermod -aG libvirt $USER

FILE="/etc/libvirt/network.conf"
CONTENT='firewall_backend = "iptables"'

if ! grep -Fxq "$CONTENT" "$FILE"; then
    echo "$CONTENT" | sudo tee -a "$FILE" > /dev/null
fi

