[general]
import = ["~/.config/alacritty/catppuccin.conf"]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Normal" }
size = 14

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 600
unfocused_hollow = false
thickness = 0.15
